apiVersion: v1
kind: Namespace
metadata:
  name: daily-report
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: daily-report
spec:
  type: NodePort
  ports:
    - port: 8011
      targetPort: 8011
      nodePort: 30233
      name: graphql-port
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: daily-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: localhost:5000/gin-gonic:latest
          ports:
            - containerPort: 8011