apiVersion: v1
kind: Namespace
metadata:
  name: daily-report
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: daily-report
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30234
      name: graphql-port
  selector:
    app: client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: daily-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: localhost:5000/nextjs:latest
          ports:
            - containerPort: 3000