apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongo-storage
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/home/jerry/Workplace/WorkTest/Git-Project/DailyReport/MongoDB/db_store"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cool-node