apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-storage
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /home/jerry/Workplace/WorkTest/Git-Project/DailyReport/MongoDB/store
      - name: NodeAffinityLabel
        value: "node-role.kubernetes.io/master"
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer